# Generated by Django 4.2.27 on 2026-02-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_task_requires_approval_task_task_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['category', 'module', 'order']},
        ),
        migrations.AddField(
            model_name='category',
            name='is_modular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_sequential',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.category')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.AddField(
            model_name='usercourse',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='user_courses', to='courses.module'),
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.module'),
        ),
    ]
