# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='task_answers/'),
        ),
        migrations.AddField(
            model_name='taskquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
