# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_task_answer_file_taskquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
