# Generated by Django 4.2.27 on 2026-08-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_tasksubmission_device_id_alter_tasksubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
