# Generated by Django 4.2.7 on 2026-01-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifacations', '0003_notification_scheduled_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('course', 'Course'), ('payment', 'Payment'), ('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=10),
        ),
    ]
